FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake libzstd-dev

COPY . /repo
WORKDIR /repo/build
RUN cmake .. -DREDIS_STORAGE_BACKEND=OFF
RUN make -j8
